### ISSUE TITLE
BS Hisame

### ISSUE THREAD

**Issue by GhstWrtr** [qwewqa/relive-simulator#71]
As soon as BS Hisame is added any simulation will end up throwing exceptions:

`java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.util.Arrays$ArrayList.get(Arrays.java:4351)
	at xyz.qwewqa.relive.simulator.core.stage.passive.UnitSkill.forLevel(UnitSkill.kt:15)
	at xyz.qwewqa.relive.simulator.core.stage.dress.DressBlueprint.create(DressBlueprint.kt:114)
	at xyz.qwewqa.relive.simulator.core.stage.SimulationParametersKt.createStageLoadout(SimulationParameters.kt:36)
	at xyz.qwewqa.relive.simulator.server.SimulateKt.createStageLoadoutOrReportError(Simulate.kt:205)
	at xyz.qwewqa.relive.simulator.server.SimulateKt.access$createStageLoadoutOrReportError(Simulate.kt:1)
	at xyz.qwewqa.relive.simulator.server.SimulateKt$simulateMany$1.invokeSuspend(Simulate.kt:119)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)`

**Comment by qwewqa** [comment]
Fixed by #72
